org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.148.0+26.1.2
modmenu_version=18.0.0-beta.1

mod_version=0.1.0-alpha.1
maven_group=io.github.teddante.forgottenfeatures
archives_base_name=forgotten-features-fabric-26.1.2
junit_version=5.11.4
